services:
  roller_tutorial:
    image: roller_tutorial
    container_name: "roller_tutorial"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Roller.Tutorial/Dockerfile
    networks:
      - tutorial_net
    depends_on:
      - postgresql
      - seq
      - redis
    ports:
      - "5200:${ASPNETCORE_HTTP_PORTS}"
    
  postgresql:
    container_name: "roller_postgresql"
    image: "postgres"
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    networks:
      - "tutorial_net"
    environment:
      TZ: "GMT+8"
      PGTZ: "GMT+8"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
  redis:
    env_file:
      - .env
    networks:
      - "tutorial_net"
    restart: unless-stopped
    container_name: "roller_redis"
    image: "redis"
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    
  seq:
    env_file:
      - .env
    image: datalust/seq:latest
    container_name: "roller_seq"
    restart: unless-stopped
    environment:
      - ACCEPT_EULA = Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH = ${SEQ_ADMINPASSWORD}
    ports:
      - "5341:80"
    networks:
      - "tutorial_net"
  seqcli:
    env_file:
      - .env
    image: datalust/seqcli:latest
    container_name: "roller_seqcli"
    command: apikey create -t newapikey --token ${SEQ_APIKEY} -s ${SEQ_URL}
    depends_on:
      - seq
    restart: on-failure:5
    networks:
      - "tutorial_net"
networks:
  tutorial_net:
    driver: bridge    