services:
  roller_tutorial:
    image: roller_tutorial
    env_file:
      - .env
    build:
      context: .
      dockerfile: Roller.Tutorial/Dockerfile
    networks:
      - tutorial_net
    depends_on:
      - postgresql
      - seq
      - redis
    ports:
      - "5200:${ASPNETCORE_HTTP_PORTS}"

  rabbitmq:
    restart: always
    image: rabbitmq:management
    networks:
      - "tutorial_net"    
    env_file:
      - .env
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
      
  postgresql:
    image: "postgres"
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env
    networks:
      - "tutorial_net"
    environment:
      TZ: "GMT+8"
      PGTZ: "GMT+8"
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

  mongo:
    image: mongo:8
    networks:
      - "tutorial_net"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
      
  redis:
    env_file:
      - .env
    networks:
      - "tutorial_net"
    restart: unless-stopped
    image: "redis"
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    
  seq:
    env_file:
      - .env
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMINPASSWORD}
    volumes:
      - ./docker/seq/data:/data
    ports:
      - "5341:80"
    networks:
      - "tutorial_net"
 
  seqcli:
    env_file:
      - .env
    image: datalust/seqcli:latest
    command: apikey create -t newapikey --token ${SEQ_APIKEY} -s ${SEQ_URL}
    depends_on:
      - seq
    restart: on-failure:5
    networks:
      - "tutorial_net"
networks:
  tutorial_net:
    driver: bridge    
